// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/datatransfer/v1/transfer.proto

// Protobuf Java Version: 4.26.0
package com.google.cloud.bigquery.datatransfer.v1;

public interface EventDrivenScheduleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.datatransfer.v1.EventDrivenSchedule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Pub/Sub subscription name used to receive events.
   * Only Google Cloud Storage data source support this option.
   * Format: projects/{project}/subscriptions/{subscription}
   * </pre>
   *
   * <code>string pubsub_subscription = 1;</code>
   * @return The pubsubSubscription.
   */
  java.lang.String getPubsubSubscription();
  /**
   * <pre>
   * Pub/Sub subscription name used to receive events.
   * Only Google Cloud Storage data source support this option.
   * Format: projects/{project}/subscriptions/{subscription}
   * </pre>
   *
   * <code>string pubsub_subscription = 1;</code>
   * @return The bytes for pubsubSubscription.
   */
  com.google.protobuf.ByteString
      getPubsubSubscriptionBytes();
}
