// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/datatransfer/v1/datasource.proto

// Protobuf Java Version: 4.26.0
package com.google.cloud.bigquery.datatransfer.v1;

/**
 * <pre>
 * A request to add transfer status messages to the run.
 * </pre>
 *
 * Protobuf type {@code google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest}
 */
public final class LogTransferRunMessagesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest)
    LogTransferRunMessagesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      LogTransferRunMessagesRequest.class.getName());
  }
  // Use LogTransferRunMessagesRequest.newBuilder() to construct.
  private LogTransferRunMessagesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LogTransferRunMessagesRequest() {
    name_ = "";
    transferMessages_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.bigquery.datatransfer.v1.DataSourceProto.internal_static_google_cloud_bigquery_datatransfer_v1_LogTransferRunMessagesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.bigquery.datatransfer.v1.DataSourceProto.internal_static_google_cloud_bigquery_datatransfer_v1_LogTransferRunMessagesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.class, com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the resource in the form:
   * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the resource in the form:
   * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSFER_MESSAGES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.cloud.bigquery.datatransfer.v1.TransferMessage> transferMessages_;
  /**
   * <pre>
   * Messages to append.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.cloud.bigquery.datatransfer.v1.TransferMessage> getTransferMessagesList() {
    return transferMessages_;
  }
  /**
   * <pre>
   * Messages to append.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder> 
      getTransferMessagesOrBuilderList() {
    return transferMessages_;
  }
  /**
   * <pre>
   * Messages to append.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
   */
  @java.lang.Override
  public int getTransferMessagesCount() {
    return transferMessages_.size();
  }
  /**
   * <pre>
   * Messages to append.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
   */
  @java.lang.Override
  public com.google.cloud.bigquery.datatransfer.v1.TransferMessage getTransferMessages(int index) {
    return transferMessages_.get(index);
  }
  /**
   * <pre>
   * Messages to append.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
   */
  @java.lang.Override
  public com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder getTransferMessagesOrBuilder(
      int index) {
    return transferMessages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    for (int i = 0; i < transferMessages_.size(); i++) {
      output.writeMessage(2, transferMessages_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    for (int i = 0; i < transferMessages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, transferMessages_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest)) {
      return super.equals(obj);
    }
    com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest other = (com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getTransferMessagesList()
        .equals(other.getTransferMessagesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getTransferMessagesCount() > 0) {
      hash = (37 * hash) + TRANSFER_MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getTransferMessagesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A request to add transfer status messages to the run.
   * </pre>
   *
   * Protobuf type {@code google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest)
      com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.bigquery.datatransfer.v1.DataSourceProto.internal_static_google_cloud_bigquery_datatransfer_v1_LogTransferRunMessagesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.bigquery.datatransfer.v1.DataSourceProto.internal_static_google_cloud_bigquery_datatransfer_v1_LogTransferRunMessagesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.class, com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.Builder.class);
    }

    // Construct using com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      if (transferMessagesBuilder_ == null) {
        transferMessages_ = java.util.Collections.emptyList();
      } else {
        transferMessages_ = null;
        transferMessagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.bigquery.datatransfer.v1.DataSourceProto.internal_static_google_cloud_bigquery_datatransfer_v1_LogTransferRunMessagesRequest_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest getDefaultInstanceForType() {
      return com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest build() {
      com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest buildPartial() {
      com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest result = new com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest result) {
      if (transferMessagesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          transferMessages_ = java.util.Collections.unmodifiableList(transferMessages_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.transferMessages_ = transferMessages_;
      } else {
        result.transferMessages_ = transferMessagesBuilder_.build();
      }
    }

    private void buildPartial0(com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest) {
        return mergeFrom((com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest other) {
      if (other == com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (transferMessagesBuilder_ == null) {
        if (!other.transferMessages_.isEmpty()) {
          if (transferMessages_.isEmpty()) {
            transferMessages_ = other.transferMessages_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTransferMessagesIsMutable();
            transferMessages_.addAll(other.transferMessages_);
          }
          onChanged();
        }
      } else {
        if (!other.transferMessages_.isEmpty()) {
          if (transferMessagesBuilder_.isEmpty()) {
            transferMessagesBuilder_.dispose();
            transferMessagesBuilder_ = null;
            transferMessages_ = other.transferMessages_;
            bitField0_ = (bitField0_ & ~0x00000002);
            transferMessagesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTransferMessagesFieldBuilder() : null;
          } else {
            transferMessagesBuilder_.addAllMessages(other.transferMessages_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.cloud.bigquery.datatransfer.v1.TransferMessage m =
                  input.readMessage(
                      com.google.cloud.bigquery.datatransfer.v1.TransferMessage.parser(),
                      extensionRegistry);
              if (transferMessagesBuilder_ == null) {
                ensureTransferMessagesIsMutable();
                transferMessages_.add(m);
              } else {
                transferMessagesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the resource in the form:
     * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the resource in the form:
     * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the resource in the form:
     * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the resource in the form:
     * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the resource in the form:
     * "projects/{project_id}/locations/{location_id}/transferConfigs/{config_id}/runs/{run_id}"
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.google.cloud.bigquery.datatransfer.v1.TransferMessage> transferMessages_ =
      java.util.Collections.emptyList();
    private void ensureTransferMessagesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        transferMessages_ = new java.util.ArrayList<com.google.cloud.bigquery.datatransfer.v1.TransferMessage>(transferMessages_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.cloud.bigquery.datatransfer.v1.TransferMessage, com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder, com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder> transferMessagesBuilder_;

    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public java.util.List<com.google.cloud.bigquery.datatransfer.v1.TransferMessage> getTransferMessagesList() {
      if (transferMessagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(transferMessages_);
      } else {
        return transferMessagesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public int getTransferMessagesCount() {
      if (transferMessagesBuilder_ == null) {
        return transferMessages_.size();
      } else {
        return transferMessagesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public com.google.cloud.bigquery.datatransfer.v1.TransferMessage getTransferMessages(int index) {
      if (transferMessagesBuilder_ == null) {
        return transferMessages_.get(index);
      } else {
        return transferMessagesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder setTransferMessages(
        int index, com.google.cloud.bigquery.datatransfer.v1.TransferMessage value) {
      if (transferMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransferMessagesIsMutable();
        transferMessages_.set(index, value);
        onChanged();
      } else {
        transferMessagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder setTransferMessages(
        int index, com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder builderForValue) {
      if (transferMessagesBuilder_ == null) {
        ensureTransferMessagesIsMutable();
        transferMessages_.set(index, builderForValue.build());
        onChanged();
      } else {
        transferMessagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder addTransferMessages(com.google.cloud.bigquery.datatransfer.v1.TransferMessage value) {
      if (transferMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransferMessagesIsMutable();
        transferMessages_.add(value);
        onChanged();
      } else {
        transferMessagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder addTransferMessages(
        int index, com.google.cloud.bigquery.datatransfer.v1.TransferMessage value) {
      if (transferMessagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTransferMessagesIsMutable();
        transferMessages_.add(index, value);
        onChanged();
      } else {
        transferMessagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder addTransferMessages(
        com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder builderForValue) {
      if (transferMessagesBuilder_ == null) {
        ensureTransferMessagesIsMutable();
        transferMessages_.add(builderForValue.build());
        onChanged();
      } else {
        transferMessagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder addTransferMessages(
        int index, com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder builderForValue) {
      if (transferMessagesBuilder_ == null) {
        ensureTransferMessagesIsMutable();
        transferMessages_.add(index, builderForValue.build());
        onChanged();
      } else {
        transferMessagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder addAllTransferMessages(
        java.lang.Iterable<? extends com.google.cloud.bigquery.datatransfer.v1.TransferMessage> values) {
      if (transferMessagesBuilder_ == null) {
        ensureTransferMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, transferMessages_);
        onChanged();
      } else {
        transferMessagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder clearTransferMessages() {
      if (transferMessagesBuilder_ == null) {
        transferMessages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        transferMessagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public Builder removeTransferMessages(int index) {
      if (transferMessagesBuilder_ == null) {
        ensureTransferMessagesIsMutable();
        transferMessages_.remove(index);
        onChanged();
      } else {
        transferMessagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder getTransferMessagesBuilder(
        int index) {
      return getTransferMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder getTransferMessagesOrBuilder(
        int index) {
      if (transferMessagesBuilder_ == null) {
        return transferMessages_.get(index);  } else {
        return transferMessagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public java.util.List<? extends com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder> 
         getTransferMessagesOrBuilderList() {
      if (transferMessagesBuilder_ != null) {
        return transferMessagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(transferMessages_);
      }
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder addTransferMessagesBuilder() {
      return getTransferMessagesFieldBuilder().addBuilder(
          com.google.cloud.bigquery.datatransfer.v1.TransferMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder addTransferMessagesBuilder(
        int index) {
      return getTransferMessagesFieldBuilder().addBuilder(
          index, com.google.cloud.bigquery.datatransfer.v1.TransferMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * Messages to append.
     * </pre>
     *
     * <code>repeated .google.cloud.bigquery.datatransfer.v1.TransferMessage transfer_messages = 2;</code>
     */
    public java.util.List<com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder> 
         getTransferMessagesBuilderList() {
      return getTransferMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.cloud.bigquery.datatransfer.v1.TransferMessage, com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder, com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder> 
        getTransferMessagesFieldBuilder() {
      if (transferMessagesBuilder_ == null) {
        transferMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.cloud.bigquery.datatransfer.v1.TransferMessage, com.google.cloud.bigquery.datatransfer.v1.TransferMessage.Builder, com.google.cloud.bigquery.datatransfer.v1.TransferMessageOrBuilder>(
                transferMessages_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        transferMessages_ = null;
      }
      return transferMessagesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest)
  private static final com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest();
  }

  public static com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LogTransferRunMessagesRequest>
      PARSER = new com.google.protobuf.AbstractParser<LogTransferRunMessagesRequest>() {
    @java.lang.Override
    public LogTransferRunMessagesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LogTransferRunMessagesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LogTransferRunMessagesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.bigquery.datatransfer.v1.LogTransferRunMessagesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

