// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/datatransfer/v1/transfer.proto

// Protobuf Java Version: 3.25.3
package com.google.cloud.bigquery.datatransfer.v1;

public interface ScheduleOptionsV2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.datatransfer.v1.ScheduleOptionsV2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Time based transfer schedule options. This is the default schedule
   * option.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.TimeBasedSchedule time_based_schedule = 1;</code>
   * @return Whether the timeBasedSchedule field is set.
   */
  boolean hasTimeBasedSchedule();
  /**
   * <pre>
   * Time based transfer schedule options. This is the default schedule
   * option.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.TimeBasedSchedule time_based_schedule = 1;</code>
   * @return The timeBasedSchedule.
   */
  com.google.cloud.bigquery.datatransfer.v1.TimeBasedSchedule getTimeBasedSchedule();
  /**
   * <pre>
   * Time based transfer schedule options. This is the default schedule
   * option.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.TimeBasedSchedule time_based_schedule = 1;</code>
   */
  com.google.cloud.bigquery.datatransfer.v1.TimeBasedScheduleOrBuilder getTimeBasedScheduleOrBuilder();

  /**
   * <pre>
   * Manual transfer schedule. If set, the transfer run will not be
   * auto-scheduled by the system, unless the client invokes
   * StartManualTransferRuns.  This is equivalent to
   * disable_auto_scheduling = true.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.ManualSchedule manual_schedule = 2;</code>
   * @return Whether the manualSchedule field is set.
   */
  boolean hasManualSchedule();
  /**
   * <pre>
   * Manual transfer schedule. If set, the transfer run will not be
   * auto-scheduled by the system, unless the client invokes
   * StartManualTransferRuns.  This is equivalent to
   * disable_auto_scheduling = true.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.ManualSchedule manual_schedule = 2;</code>
   * @return The manualSchedule.
   */
  com.google.cloud.bigquery.datatransfer.v1.ManualSchedule getManualSchedule();
  /**
   * <pre>
   * Manual transfer schedule. If set, the transfer run will not be
   * auto-scheduled by the system, unless the client invokes
   * StartManualTransferRuns.  This is equivalent to
   * disable_auto_scheduling = true.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.ManualSchedule manual_schedule = 2;</code>
   */
  com.google.cloud.bigquery.datatransfer.v1.ManualScheduleOrBuilder getManualScheduleOrBuilder();

  /**
   * <pre>
   * Event driven transfer schedule options. If set, the transfer will be
   * scheduled upon events arrial.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.EventDrivenSchedule event_driven_schedule = 3;</code>
   * @return Whether the eventDrivenSchedule field is set.
   */
  boolean hasEventDrivenSchedule();
  /**
   * <pre>
   * Event driven transfer schedule options. If set, the transfer will be
   * scheduled upon events arrial.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.EventDrivenSchedule event_driven_schedule = 3;</code>
   * @return The eventDrivenSchedule.
   */
  com.google.cloud.bigquery.datatransfer.v1.EventDrivenSchedule getEventDrivenSchedule();
  /**
   * <pre>
   * Event driven transfer schedule options. If set, the transfer will be
   * scheduled upon events arrial.
   * </pre>
   *
   * <code>.google.cloud.bigquery.datatransfer.v1.EventDrivenSchedule event_driven_schedule = 3;</code>
   */
  com.google.cloud.bigquery.datatransfer.v1.EventDrivenScheduleOrBuilder getEventDrivenScheduleOrBuilder();

  com.google.cloud.bigquery.datatransfer.v1.ScheduleOptionsV2.ScheduleCase getScheduleCase();
}
